cmake_minimum_required(VERSION 3.25)
if(NOT IS_ABSOLUTE "${TEST_ROOT}" OR NOT IS_DIRECTORY "${SOURCE_ROOT}/scripts")
    message(FATAL_ERROR "SOURCE_ROOT and absolute TEST_ROOT are required")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(work "${TEST_ROOT}/${suffix}")
file(MAKE_DIRECTORY "${work}/existing" "${work}/fixture/scripts")
file(WRITE "${work}/existing/sentinel" "preserve this checkout\n")
set(helper "${SOURCE_ROOT}/scripts/bootstrap-vcpkg.cmake")
function(expect_failure root diagnostic)
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env "VCPKG_ROOT=${root}"
            "${CMAKE_COMMAND}" -P "${helper}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    string(FIND "${output}${error}" "${diagnostic}" position)
    if("${result}" STREQUAL "0" OR position EQUAL -1)
        message(FATAL_ERROR "Unexpected bootstrap result: ${result}\n${output}${error}")
    endif()
endfunction()
expect_failure("" "VCPKG_ROOT must name a new")
expect_failure("relative-checkout" "VCPKG_ROOT must be absolute")
expect_failure("${work}/existing" "must not already exist")
file(READ "${work}/existing/sentinel" sentinel)
if(NOT sentinel STREQUAL "preserve this checkout\n")
    message(FATAL_ERROR "Existing checkout was changed")
endif()
configure_file("${helper}" "${work}/fixture/scripts/bootstrap-vcpkg.cmake" COPYONLY)
set(helper "${work}/fixture/scripts/bootstrap-vcpkg.cmake")
foreach(baseline IN ITEMS main 1234567890 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)
    file(WRITE "${work}/fixture/vcpkg.json" "{\"builtin-baseline\":\"${baseline}\"}\n")
    expect_failure("${work}/new-checkout" "builtin-baseline must be one lowercase immutable")
    if(EXISTS "${work}/new-checkout")
        message(FATAL_ERROR "Invalid manifest created a checkout")
    endif()
endforeach()
message(STATUS "Bootstrap rejects missing/relative/existing destinations and mutable or malformed pins")
