# Shared CI bootstrap. The manifest is the single source of the registry pin.
cmake_minimum_required(VERSION 3.25)
if("$ENV{VCPKG_ROOT}" STREQUAL "")
    message(FATAL_ERROR "VCPKG_ROOT must name a new, isolated checkout directory")
endif()
file(TO_CMAKE_PATH "$ENV{VCPKG_ROOT}" vcpkg_root)
if(NOT IS_ABSOLUTE "${vcpkg_root}" OR EXISTS "${vcpkg_root}")
    message(FATAL_ERROR "VCPKG_ROOT must be absolute and must not already exist")
endif()
file(READ "${CMAKE_CURRENT_LIST_DIR}/../vcpkg.json" manifest)
string(JSON baseline GET "${manifest}" builtin-baseline)
string(LENGTH "${baseline}" baseline_length)
if(NOT baseline_length EQUAL 40 OR NOT baseline MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "builtin-baseline must be one lowercase immutable Git object ID")
endif()
if(CMAKE_HOST_WIN32)
    find_program(GIT_EXECUTABLE NAMES git.exe HINTS "C:/Program Files/Git/cmd")
endif()
find_package(Git REQUIRED)
function(run_checked)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE result COMMAND_ECHO STDOUT TIMEOUT 300)
    if(NOT "${result}" STREQUAL "0")
        message(FATAL_ERROR "vcpkg bootstrap command failed: ${result}")
    endif()
endfunction()
run_checked("${GIT_EXECUTABLE}" init "${vcpkg_root}")
run_checked("${GIT_EXECUTABLE}" -C "${vcpkg_root}" remote add origin
    https://github.com/microsoft/vcpkg.git)
run_checked("${GIT_EXECUTABLE}" -C "${vcpkg_root}" fetch --depth 1 origin "${baseline}")
run_checked("${GIT_EXECUTABLE}" -C "${vcpkg_root}" checkout --detach FETCH_HEAD)
if(CMAKE_HOST_WIN32)
    run_checked(cmd /c "${vcpkg_root}/bootstrap-vcpkg.bat" -disableMetrics)
else()
    run_checked("${vcpkg_root}/bootstrap-vcpkg.sh" -disableMetrics)
endif()
message(STATUS "Bootstrapped vcpkg registry ${baseline}")
